// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
namespace P2
{
    
    #region Windows Form Designer generated code
    public partial class CalcForm
    {
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.equiTitle = new System.Windows.Forms.Label();
            this.idealGasTitle = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.partialpressure = new System.Windows.Forms.Label();
            this.label22 = new System.Windows.Forms.Label();
            this.molarmass = new System.Windows.Forms.Label();
            this.label23 = new System.Windows.Forms.Label();
            this.label25 = new System.Windows.Forms.Label();
            this.gasConst = new System.Windows.Forms.Label();
            this.label27 = new System.Windows.Forms.Label();
            this.temperature = new System.Windows.Forms.Label();
            this.label29 = new System.Windows.Forms.Label();
            this.Volume = new System.Windows.Forms.Label();
            this.label31 = new System.Windows.Forms.Label();
            this.equiFracResult = new System.Windows.Forms.Label();
            this.pAmmoniaEqui = new System.Windows.Forms.Label();
            this.label26 = new System.Windows.Forms.Label();
            this.pNitrogenEqui = new System.Windows.Forms.Label();
            this.label30 = new System.Windows.Forms.Label();
            this.pHydrogenEqui = new System.Windows.Forms.Label();
            this.label33 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.RRConst = new System.Windows.Forms.Label();
            this.label24 = new System.Windows.Forms.Label();
            this.label28 = new System.Windows.Forms.Label();
            this.activationEnergy = new System.Windows.Forms.Label();
            this.label34 = new System.Windows.Forms.Label();
            this.gasConstRR = new System.Windows.Forms.Label();
            this.label36 = new System.Windows.Forms.Label();
            this.preExponentialFactor = new System.Windows.Forms.Label();
            this.label38 = new System.Windows.Forms.Label();
            this.temperatureRR = new System.Windows.Forms.Label();
            this.label40 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label32 = new System.Windows.Forms.Label();
            this.label35 = new System.Windows.Forms.Label();
            this.label37 = new System.Windows.Forms.Label();
            this.label39 = new System.Windows.Forms.Label();
            this.label41 = new System.Windows.Forms.Label();
            this.label42 = new System.Windows.Forms.Label();
            this.label43 = new System.Windows.Forms.Label();
            this.label44 = new System.Windows.Forms.Label();
            this.label45 = new System.Windows.Forms.Label();
            this.label21 = new System.Windows.Forms.Label();
            this.entropiLabel = new System.Windows.Forms.Label();
            this.label47 = new System.Windows.Forms.Label();
            this.gasConstEqui = new System.Windows.Forms.Label();
            this.label49 = new System.Windows.Forms.Label();
            this.entalpiLabel = new System.Windows.Forms.Label();
            this.label51 = new System.Windows.Forms.Label();
            this.gasConstEqui2 = new System.Windows.Forms.Label();
            this.label54 = new System.Windows.Forms.Label();
            this.label55 = new System.Windows.Forms.Label();
            this.temperatureEqui = new System.Windows.Forms.Label();
            this.label57 = new System.Windows.Forms.Label();
            this.equiConst = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Italic);
            this.label1.Location = new System.Drawing.Point(16, 268);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(24, 23);
            this.label1.TabIndex = 0;
            this.label1.Text = "Y =";
            // 
            // label2
            // 
            this.label2.Location = new System.Drawing.Point(56, 252);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(56, 16);
            this.label2.TabIndex = 1;
            this.label2.Text = "p(NH₃)²";
            // 
            // label3
            // 
            this.label3.Location = new System.Drawing.Point(48, 260);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(88, 15);
            this.label3.TabIndex = 2;
            this.label3.Text = "____________";
            // 
            // label4
            // 
            this.label4.Location = new System.Drawing.Point(48, 276);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(88, 24);
            this.label4.TabIndex = 3;
            this.label4.Text = "p(N₂)² • p(H₂)³";
            // 
            // label6
            // 
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Italic);
            this.label6.Location = new System.Drawing.Point(16, 56);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(24, 23);
            this.label6.TabIndex = 0;
            this.label6.Text = "p =";
            // 
            // label7
            // 
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Italic);
            this.label7.Location = new System.Drawing.Point(56, 40);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(56, 16);
            this.label7.TabIndex = 1;
            this.label7.Text = "n • R • T";
            // 
            // label8
            // 
            this.label8.Location = new System.Drawing.Point(48, 48);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(100, 15);
            this.label8.TabIndex = 2;
            this.label8.Text = "__________";
            // 
            // label9
            // 
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Italic);
            this.label9.Location = new System.Drawing.Point(72, 64);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(16, 23);
            this.label9.TabIndex = 3;
            this.label9.Text = "V";
            // 
            // equiTitle
            // 
            this.equiTitle.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))));
            this.equiTitle.Location = new System.Drawing.Point(368, 227);
            this.equiTitle.Name = "equiTitle";
            this.equiTitle.Size = new System.Drawing.Size(239, 16);
            this.equiTitle.TabIndex = 4;
            this.equiTitle.Text = "Ligevægtsbrøken:";
            // 
            // idealGasTitle
            // 
            this.idealGasTitle.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))));
            this.idealGasTitle.Location = new System.Drawing.Point(368, 16);
            this.idealGasTitle.Name = "idealGasTitle";
            this.idealGasTitle.Size = new System.Drawing.Size(239, 16);
            this.idealGasTitle.TabIndex = 4;
            this.idealGasTitle.Text = "Idealgasligningen:";
            // 
            // label11
            // 
            this.label11.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))));
            this.label11.Location = new System.Drawing.Point(16, 323);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(148, 16);
            this.label11.TabIndex = 5;
            this.label11.Text = "Hastighedskonstanten:";
            // 
            // label12
            // 
            this.label12.Location = new System.Drawing.Point(16, 363);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(8, 16);
            this.label12.TabIndex = 6;
            this.label12.Text = "K";
            // 
            // label13
            // 
            this.label13.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F);
            this.label13.Location = new System.Drawing.Point(24, 371);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(8, 8);
            this.label13.TabIndex = 7;
            this.label13.Text = "h";
            // 
            // label14
            // 
            this.label14.Location = new System.Drawing.Point(38, 363);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(16, 16);
            this.label14.TabIndex = 8;
            this.label14.Text = "=";
            // 
            // label15
            // 
            this.label15.Location = new System.Drawing.Point(72, 363);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(24, 16);
            this.label15.TabIndex = 9;
            this.label15.Text = "e ⁻";
            // 
            // label17
            // 
            this.label17.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label17.Location = new System.Drawing.Point(102, 346);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(18, 10);
            this.label17.TabIndex = 11;
            this.label17.Text = "Eₐ";
            // 
            // label16
            // 
            this.label16.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label16.Location = new System.Drawing.Point(96, 350);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(40, 10);
            this.label16.TabIndex = 12;
            this.label16.Text = "______";
            // 
            // label18
            // 
            this.label18.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label18.Location = new System.Drawing.Point(96, 359);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(40, 16);
            this.label18.TabIndex = 13;
            this.label18.Text = "R • T";
            // 
            // label19
            // 
            this.label19.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.label19.Location = new System.Drawing.Point(336, -8);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(15, 447);
            this.label19.TabIndex = 14;
            // 
            // label20
            // 
            this.label20.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))));
            this.label20.Location = new System.Drawing.Point(16, 16);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(128, 16);
            this.label20.TabIndex = 4;
            this.label20.Text = "Idealgasligningen:";
            // 
            // partialpressure
            // 
            this.partialpressure.Location = new System.Drawing.Point(368, 56);
            this.partialpressure.Name = "partialpressure";
            this.partialpressure.Size = new System.Drawing.Size(48, 16);
            this.partialpressure.TabIndex = 15;
            this.partialpressure.Text = "Partial";
            // 
            // label22
            // 
            this.label22.Location = new System.Drawing.Point(416, 56);
            this.label22.Name = "label22";
            this.label22.Size = new System.Drawing.Size(16, 16);
            this.label22.TabIndex = 16;
            this.label22.Text = "=";
            // 
            // molarmass
            // 
            this.molarmass.Location = new System.Drawing.Point(432, 40);
            this.molarmass.Name = "molarmass";
            this.molarmass.Size = new System.Drawing.Size(64, 16);
            this.molarmass.TabIndex = 18;
            this.molarmass.Text = "molar";
            // 
            // label23
            // 
            this.label23.Location = new System.Drawing.Point(72, 40);
            this.label23.Name = "label23";
            this.label23.Size = new System.Drawing.Size(100, 23);
            this.label23.TabIndex = 19;
            this.label23.Text = "label23";
            // 
            // label25
            // 
            this.label25.Location = new System.Drawing.Point(576, 40);
            this.label25.Name = "label25";
            this.label25.Size = new System.Drawing.Size(8, 16);
            this.label25.TabIndex = 20;
            this.label25.Text = "•";
            // 
            // gasConst
            // 
            this.gasConst.Location = new System.Drawing.Point(512, 40);
            this.gasConst.Name = "gasConst";
            this.gasConst.Size = new System.Drawing.Size(56, 16);
            this.gasConst.TabIndex = 21;
            this.gasConst.Text = "gasConst";
            // 
            // label27
            // 
            this.label27.Location = new System.Drawing.Point(496, 40);
            this.label27.Name = "label27";
            this.label27.Size = new System.Drawing.Size(8, 16);
            this.label27.TabIndex = 20;
            this.label27.Text = "•";
            // 
            // temperature
            // 
            this.temperature.Location = new System.Drawing.Point(592, 40);
            this.temperature.Name = "temperature";
            this.temperature.Size = new System.Drawing.Size(40, 16);
            this.temperature.TabIndex = 22;
            this.temperature.Text = "Temp";
            // 
            // label29
            // 
            this.label29.Location = new System.Drawing.Point(432, 48);
            this.label29.Name = "label29";
            this.label29.Size = new System.Drawing.Size(192, 15);
            this.label29.TabIndex = 23;
            this.label29.Text = "_________________________________";
            // 
            // Volume
            // 
            this.Volume.Location = new System.Drawing.Point(496, 64);
            this.Volume.Name = "Volume";
            this.Volume.Size = new System.Drawing.Size(56, 16);
            this.Volume.TabIndex = 24;
            this.Volume.Text = "Volumen";
            // 
            // label31
            // 
            this.label31.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))));
            this.label31.Location = new System.Drawing.Point(16, 228);
            this.label31.Name = "label31";
            this.label31.Size = new System.Drawing.Size(192, 15);
            this.label31.TabIndex = 4;
            this.label31.Text = "Ligevægtsbrøken:";
            // 
            // equiFracResult
            // 
            this.equiFracResult.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.equiFracResult.Location = new System.Drawing.Point(368, 267);
            this.equiFracResult.Name = "equiFracResult";
            this.equiFracResult.Size = new System.Drawing.Size(80, 15);
            this.equiFracResult.TabIndex = 25;
            this.equiFracResult.Text = "equiConst";
            // 
            // pAmmoniaEqui
            // 
            this.pAmmoniaEqui.Location = new System.Drawing.Point(496, 258);
            this.pAmmoniaEqui.Name = "pAmmoniaEqui";
            this.pAmmoniaEqui.Size = new System.Drawing.Size(100, 16);
            this.pAmmoniaEqui.TabIndex = 26;
            this.pAmmoniaEqui.Text = "pNH3^2";
            // 
            // label26
            // 
            this.label26.Location = new System.Drawing.Point(465, 267);
            this.label26.Name = "label26";
            this.label26.Size = new System.Drawing.Size(189, 15);
            this.label26.TabIndex = 27;
            this.label26.Text = "______________________________________________";
            // 
            // pNitrogenEqui
            // 
            this.pNitrogenEqui.Location = new System.Drawing.Point(471, 284);
            this.pNitrogenEqui.Name = "pNitrogenEqui";
            this.pNitrogenEqui.Size = new System.Drawing.Size(89, 24);
            this.pNitrogenEqui.TabIndex = 28;
            this.pNitrogenEqui.Text = "pN2^2";
            // 
            // label30
            // 
            this.label30.Location = new System.Drawing.Point(553, 284);
            this.label30.Name = "label30";
            this.label30.Size = new System.Drawing.Size(19, 24);
            this.label30.TabIndex = 29;
            this.label30.Text = " •";
            // 
            // pHydrogenEqui
            // 
            this.pHydrogenEqui.Location = new System.Drawing.Point(578, 282);
            this.pHydrogenEqui.Name = "pHydrogenEqui";
            this.pHydrogenEqui.Size = new System.Drawing.Size(100, 24);
            this.pHydrogenEqui.TabIndex = 30;
            this.pHydrogenEqui.Text = "PH2^3";
            // 
            // label33
            // 
            this.label33.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label33.Location = new System.Drawing.Point(443, 267);
            this.label33.Name = "label33";
            this.label33.Size = new System.Drawing.Size(16, 23);
            this.label33.TabIndex = 31;
            this.label33.Text = "=";
            // 
            // label5
            // 
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))));
            this.label5.Location = new System.Drawing.Point(368, 323);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(148, 16);
            this.label5.TabIndex = 32;
            this.label5.Text = "Hastighedskonstanten:";
            // 
            // RRConst
            // 
            this.RRConst.Location = new System.Drawing.Point(368, 363);
            this.RRConst.Name = "RRConst";
            this.RRConst.Size = new System.Drawing.Size(44, 16);
            this.RRConst.TabIndex = 33;
            this.RRConst.Text = "K_h";
            // 
            // label24
            // 
            this.label24.Location = new System.Drawing.Point(412, 363);
            this.label24.Name = "label24";
            this.label24.Size = new System.Drawing.Size(16, 16);
            this.label24.TabIndex = 35;
            this.label24.Text = "=";
            // 
            // label28
            // 
            this.label28.Location = new System.Drawing.Point(505, 363);
            this.label28.Name = "label28";
            this.label28.Size = new System.Drawing.Size(24, 16);
            this.label28.TabIndex = 36;
            this.label28.Text = "e ⁻";
            // 
            // activationEnergy
            // 
            this.activationEnergy.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.activationEnergy.Location = new System.Drawing.Point(548, 339);
            this.activationEnergy.Name = "activationEnergy";
            this.activationEnergy.Size = new System.Drawing.Size(74, 16);
            this.activationEnergy.TabIndex = 37;
            this.activationEnergy.Text = "Eₐ";
            // 
            // label34
            // 
            this.label34.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label34.Location = new System.Drawing.Point(529, 347);
            this.label34.Name = "label34";
            this.label34.Size = new System.Drawing.Size(85, 16);
            this.label34.TabIndex = 38;
            this.label34.Text = "____________________";
            // 
            // gasConstRR
            // 
            this.gasConstRR.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gasConstRR.Location = new System.Drawing.Point(530, 359);
            this.gasConstRR.Name = "gasConstRR";
            this.gasConstRR.Size = new System.Drawing.Size(40, 16);
            this.gasConstRR.TabIndex = 39;
            this.gasConstRR.Text = "R";
            // 
            // label36
            // 
            this.label36.AutoSize = true;
            this.label36.Location = new System.Drawing.Point(49, 363);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(26, 13);
            this.label36.TabIndex = 41;
            this.label36.Text = "K₀ •";
            // 
            // preExponentialFactor
            // 
            this.preExponentialFactor.AutoSize = true;
            this.preExponentialFactor.Location = new System.Drawing.Point(433, 363);
            this.preExponentialFactor.Name = "preExponentialFactor";
            this.preExponentialFactor.Size = new System.Drawing.Size(17, 13);
            this.preExponentialFactor.TabIndex = 42;
            this.preExponentialFactor.Text = "K₀";
            // 
            // label38
            // 
            this.label38.AutoSize = true;
            this.label38.Location = new System.Drawing.Point(496, 363);
            this.label38.Name = "label38";
            this.label38.Size = new System.Drawing.Size(13, 13);
            this.label38.TabIndex = 43;
            this.label38.Text = "•";
            // 
            // temperatureRR
            // 
            this.temperatureRR.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.temperatureRR.Location = new System.Drawing.Point(592, 359);
            this.temperatureRR.Name = "temperatureRR";
            this.temperatureRR.Size = new System.Drawing.Size(40, 16);
            this.temperatureRR.TabIndex = 44;
            this.temperatureRR.Text = "T";
            // 
            // label40
            // 
            this.label40.AutoSize = true;
            this.label40.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label40.Location = new System.Drawing.Point(578, 359);
            this.label40.Name = "label40";
            this.label40.Size = new System.Drawing.Size(8, 9);
            this.label40.TabIndex = 45;
            this.label40.Text = "•";
            // 
            // label10
            // 
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))));
            this.label10.Location = new System.Drawing.Point(16, 119);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(148, 15);
            this.label10.TabIndex = 46;
            this.label10.Text = "Ligevægtskonstanten:";
            // 
            // label32
            // 
            this.label32.AutoSize = true;
            this.label32.Location = new System.Drawing.Point(23, 180);
            this.label32.Name = "label32";
            this.label32.Size = new System.Drawing.Size(22, 13);
            this.label32.TabIndex = 48;
            this.label32.Text = "k =";
            // 
            // label35
            // 
            this.label35.Location = new System.Drawing.Point(48, 181);
            this.label35.Name = "label35";
            this.label35.Size = new System.Drawing.Size(10, 16);
            this.label35.TabIndex = 49;
            this.label35.Text = "e";
            // 
            // label37
            // 
            this.label37.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label37.Location = new System.Drawing.Point(71, 161);
            this.label37.Name = "label37";
            this.label37.Size = new System.Drawing.Size(25, 10);
            this.label37.TabIndex = 50;
            this.label37.Text = "∆H";
            // 
            // label39
            // 
            this.label39.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label39.Location = new System.Drawing.Point(63, 164);
            this.label39.Name = "label39";
            this.label39.Size = new System.Drawing.Size(40, 16);
            this.label39.TabIndex = 51;
            this.label39.Text = "______";
            // 
            // label41
            // 
            this.label41.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label41.Location = new System.Drawing.Point(64, 173);
            this.label41.Name = "label41";
            this.label41.Size = new System.Drawing.Size(40, 16);
            this.label41.TabIndex = 52;
            this.label41.Text = "R • T";
            // 
            // label42
            // 
            this.label42.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label42.Location = new System.Drawing.Point(110, 160);
            this.label42.Name = "label42";
            this.label42.Size = new System.Drawing.Size(32, 10);
            this.label42.TabIndex = 53;
            this.label42.Text = "∆S";
            // 
            // label43
            // 
            this.label43.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label43.Location = new System.Drawing.Point(102, 164);
            this.label43.Name = "label43";
            this.label43.Size = new System.Drawing.Size(40, 16);
            this.label43.TabIndex = 54;
            this.label43.Text = "______";
            // 
            // label44
            // 
            this.label44.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label44.Location = new System.Drawing.Point(110, 173);
            this.label44.Name = "label44";
            this.label44.Size = new System.Drawing.Size(24, 16);
            this.label44.TabIndex = 55;
            this.label44.Text = "R";
            // 
            // label45
            // 
            this.label45.AutoSize = true;
            this.label45.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F);
            this.label45.Location = new System.Drawing.Point(93, 169);
            this.label45.Name = "label45";
            this.label45.Size = new System.Drawing.Size(10, 9);
            this.label45.TabIndex = 56;
            this.label45.Text = "+";
            // 
            // label21
            // 
            this.label21.AutoSize = true;
            this.label21.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label21.Location = new System.Drawing.Point(540, 169);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(10, 9);
            this.label21.TabIndex = 66;
            this.label21.Text = "+";
            // 
            // entropiLabel
            // 
            this.entropiLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.entropiLabel.Location = new System.Drawing.Point(567, 157);
            this.entropiLabel.Name = "entropiLabel";
            this.entropiLabel.Size = new System.Drawing.Size(55, 16);
            this.entropiLabel.TabIndex = 63;
            this.entropiLabel.Text = "∆S";
            // 
            // label47
            // 
            this.label47.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label47.Location = new System.Drawing.Point(559, 165);
            this.label47.Name = "label47";
            this.label47.Size = new System.Drawing.Size(63, 16);
            this.label47.TabIndex = 64;
            this.label47.Text = "____________";
            // 
            // gasConstEqui
            // 
            this.gasConstEqui.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gasConstEqui.Location = new System.Drawing.Point(562, 177);
            this.gasConstEqui.Name = "gasConstEqui";
            this.gasConstEqui.Size = new System.Drawing.Size(45, 16);
            this.gasConstEqui.TabIndex = 65;
            this.gasConstEqui.Text = "R";
            // 
            // label49
            // 
            this.label49.Location = new System.Drawing.Point(428, 182);
            this.label49.Name = "label49";
            this.label49.Size = new System.Drawing.Size(10, 16);
            this.label49.TabIndex = 59;
            this.label49.Text = "e";
            // 
            // entalpiLabel
            // 
            this.entalpiLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.entalpiLabel.Location = new System.Drawing.Point(466, 156);
            this.entalpiLabel.Name = "entalpiLabel";
            this.entalpiLabel.Size = new System.Drawing.Size(64, 16);
            this.entalpiLabel.TabIndex = 60;
            this.entalpiLabel.Text = "∆H";
            // 
            // label51
            // 
            this.label51.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label51.Location = new System.Drawing.Point(443, 165);
            this.label51.Name = "label51";
            this.label51.Size = new System.Drawing.Size(94, 16);
            this.label51.TabIndex = 61;
            this.label51.Text = "_____________________";
            // 
            // gasConstEqui2
            // 
            this.gasConstEqui2.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gasConstEqui2.Location = new System.Drawing.Point(444, 177);
            this.gasConstEqui2.Name = "gasConstEqui2";
            this.gasConstEqui2.Size = new System.Drawing.Size(45, 12);
            this.gasConstEqui2.TabIndex = 62;
            this.gasConstEqui2.Text = "R";
            // 
            // label54
            // 
            this.label54.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))));
            this.label54.Location = new System.Drawing.Point(368, 119);
            this.label54.Name = "label54";
            this.label54.Size = new System.Drawing.Size(148, 15);
            this.label54.TabIndex = 57;
            this.label54.Text = "Ligevægtskonstanten:";
            // 
            // label55
            // 
            this.label55.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label55.Location = new System.Drawing.Point(494, 177);
            this.label55.Name = "label55";
            this.label55.Size = new System.Drawing.Size(10, 16);
            this.label55.TabIndex = 67;
            this.label55.Text = "•";
            // 
            // temperatureEqui
            // 
            this.temperatureEqui.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.temperatureEqui.Location = new System.Drawing.Point(505, 177);
            this.temperatureEqui.Name = "temperatureEqui";
            this.temperatureEqui.Size = new System.Drawing.Size(32, 16);
            this.temperatureEqui.TabIndex = 68;
            this.temperatureEqui.Text = "T";
            // 
            // label57
            // 
            this.label57.AutoSize = true;
            this.label57.Location = new System.Drawing.Point(409, 180);
            this.label57.Name = "label57";
            this.label57.Size = new System.Drawing.Size(13, 13);
            this.label57.TabIndex = 69;
            this.label57.Text = "=";
            // 
            // equiConst
            // 
            this.equiConst.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.equiConst.Location = new System.Drawing.Point(368, 178);
            this.equiConst.Name = "equiConst";
            this.equiConst.Size = new System.Drawing.Size(48, 15);
            this.equiConst.TabIndex = 70;
            this.equiConst.Text = "k";
            // 
            // CalcForm
            // 
            this.ClientSize = new System.Drawing.Size(681, 390);
            this.Controls.Add(this.label40);
            this.Controls.Add(this.temperatureRR);
            this.Controls.Add(this.gasConstRR);
            this.Controls.Add(this.label34);
            this.Controls.Add(this.label55);
            this.Controls.Add(this.temperatureEqui);
            this.Controls.Add(this.gasConstEqui);
            this.Controls.Add(this.label47);
            this.Controls.Add(this.gasConstEqui2);
            this.Controls.Add(this.label51);
            this.Controls.Add(this.label45);
            this.Controls.Add(this.label41);
            this.Controls.Add(this.label44);
            this.Controls.Add(this.label57);
            this.Controls.Add(this.equiConst);
            this.Controls.Add(this.label21);
            this.Controls.Add(this.entropiLabel);
            this.Controls.Add(this.label49);
            this.Controls.Add(this.entalpiLabel);
            this.Controls.Add(this.label54);
            this.Controls.Add(this.label42);
            this.Controls.Add(this.label43);
            this.Controls.Add(this.label35);
            this.Controls.Add(this.label37);
            this.Controls.Add(this.label39);
            this.Controls.Add(this.label32);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label38);
            this.Controls.Add(this.preExponentialFactor);
            this.Controls.Add(this.label36);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.RRConst);
            this.Controls.Add(this.label24);
            this.Controls.Add(this.label28);
            this.Controls.Add(this.activationEnergy);
            this.Controls.Add(this.label33);
            this.Controls.Add(this.pHydrogenEqui);
            this.Controls.Add(this.label30);
            this.Controls.Add(this.equiFracResult);
            this.Controls.Add(this.pAmmoniaEqui);
            this.Controls.Add(this.label26);
            this.Controls.Add(this.pNitrogenEqui);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.equiTitle);
            this.Controls.Add(this.idealGasTitle);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label15);
            this.Controls.Add(this.label17);
            this.Controls.Add(this.label16);
            this.Controls.Add(this.label18);
            this.Controls.Add(this.label19);
            this.Controls.Add(this.label20);
            this.Controls.Add(this.partialpressure);
            this.Controls.Add(this.label22);
            this.Controls.Add(this.molarmass);
            this.Controls.Add(this.label23);
            this.Controls.Add(this.label25);
            this.Controls.Add(this.gasConst);
            this.Controls.Add(this.label27);
            this.Controls.Add(this.temperature);
            this.Controls.Add(this.label29);
            this.Controls.Add(this.Volume);
            this.Controls.Add(this.label31);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Location = new System.Drawing.Point(-104, 0);
            this.Name = "CalcForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Udregninger";
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label equiTitle;
        private System.Windows.Forms.Label idealGasTitle;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.Label partialpressure;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.Label molarmass;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.Label gasConst;
        private System.Windows.Forms.Label label27;
        private System.Windows.Forms.Label temperature;
        private System.Windows.Forms.Label label29;
        private System.Windows.Forms.Label Volume;
        private System.Windows.Forms.Label label31;
        private System.Windows.Forms.Label equiFracResult;
        private System.Windows.Forms.Label pAmmoniaEqui;
        private System.Windows.Forms.Label label26;
        private System.Windows.Forms.Label pNitrogenEqui;
        private System.Windows.Forms.Label label30;
        private System.Windows.Forms.Label pHydrogenEqui;
        private System.Windows.Forms.Label label33;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label RRConst;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.Label label28;
        private System.Windows.Forms.Label activationEnergy;
        private System.Windows.Forms.Label label34;
        private System.Windows.Forms.Label gasConstRR;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.Label preExponentialFactor;
        private System.Windows.Forms.Label label38;
        private System.Windows.Forms.Label temperatureRR;
        private System.Windows.Forms.Label label40;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label32;
        private System.Windows.Forms.Label label35;
        private System.Windows.Forms.Label label37;
        private System.Windows.Forms.Label label39;
        private System.Windows.Forms.Label label41;
        private System.Windows.Forms.Label label42;
        private System.Windows.Forms.Label label43;
        private System.Windows.Forms.Label label44;
        private System.Windows.Forms.Label label45;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.Label entropiLabel;
        private System.Windows.Forms.Label label47;
        private System.Windows.Forms.Label gasConstEqui;
        private System.Windows.Forms.Label label49;
        private System.Windows.Forms.Label entalpiLabel;
        private System.Windows.Forms.Label label51;
        private System.Windows.Forms.Label gasConstEqui2;
        private System.Windows.Forms.Label label54;
        private System.Windows.Forms.Label label55;
        private System.Windows.Forms.Label temperatureEqui;
        private System.Windows.Forms.Label label57;
        private System.Windows.Forms.Label equiConst;
    }
    #endregion
}
