// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace P2
{
    
    #region Windows Form Designer generated code
    public partial class CalcForm
    {

        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.partialpressure = new System.Windows.Forms.Label();
            this.label22 = new System.Windows.Forms.Label();
            this.molarmassNitrogen = new System.Windows.Forms.Label();
            this.label23 = new System.Windows.Forms.Label();
            this.label25 = new System.Windows.Forms.Label();
            this.gasConst = new System.Windows.Forms.Label();
            this.label27 = new System.Windows.Forms.Label();
            this.temperature = new System.Windows.Forms.Label();
            this.label29 = new System.Windows.Forms.Label();
            this.Volume = new System.Windows.Forms.Label();
            this.label31 = new System.Windows.Forms.Label();
            // 
            // label1
            // 
            this.label1.Name = "label1";
            this.label1.Location = new System.Drawing.Point(16, 160);
            this.label1.Image = null;
            this.label1.TabIndex = 0;
            this.label1.Size = new System.Drawing.Size(24, 23);
            this.label1.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            this.label1.Text = "Y =";
            // 
            // label2
            // 
            this.label2.Name = "label2";
            this.label2.Location = new System.Drawing.Point(56, 144);
            this.label2.Image = null;
            this.label2.TabIndex = 1;
            this.label2.Size = new System.Drawing.Size(56, 16);
            this.label2.Text = "p(NH₃)²";
            // 
            // label3
            // 
            this.label3.Name = "label3";
            this.label3.Location = new System.Drawing.Point(48, 152);
            this.label3.Image = null;
            this.label3.TabIndex = 2;
            this.label3.Size = new System.Drawing.Size(88, 15);
            this.label3.Text = "____________";
            // 
            // label4
            // 
            this.label4.Name = "label4";
            this.label4.Location = new System.Drawing.Point(48, 168);
            this.label4.Image = null;
            this.label4.TabIndex = 3;
            this.label4.Size = new System.Drawing.Size(88, 24);
            this.label4.Text = "p(N₂)² • p(H₂)³";
            // 
            // label6
            // 
            this.label6.Name = "label6";
            this.label6.Location = new System.Drawing.Point(16, 56);
            this.label6.Image = null;
            this.label6.TabIndex = 0;
            this.label6.Size = new System.Drawing.Size(24, 23);
            this.label6.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            this.label6.Text = "p =";
            // 
            // label7
            // 
            this.label7.Name = "label7";
            this.label7.Location = new System.Drawing.Point(56, 40);
            this.label7.Image = null;
            this.label7.TabIndex = 1;
            this.label7.Size = new System.Drawing.Size(56, 16);
            this.label7.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            this.label7.Text = "n • R • T";
            // 
            // label8
            // 
            this.label8.Name = "label8";
            this.label8.Location = new System.Drawing.Point(48, 48);
            this.label8.Image = null;
            this.label8.TabIndex = 2;
            this.label8.Size = new System.Drawing.Size(100, 15);
            this.label8.Text = "__________";
            // 
            // label9
            // 
            this.label9.Name = "label9";
            this.label9.Location = new System.Drawing.Point(72, 64);
            this.label9.Image = null;
            this.label9.TabIndex = 3;
            this.label9.Size = new System.Drawing.Size(16, 23);
            this.label9.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            this.label9.Text = "V";
            // 
            // label5
            // 
            this.label5.Name = "label5";
            this.label5.Location = new System.Drawing.Point(368, 120);
            this.label5.Image = null;
            this.label5.TabIndex = 4;
            this.label5.Size = new System.Drawing.Size(128, 16);
            this.label5.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, (System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline), System.Drawing.GraphicsUnit.Point);
            this.label5.Text = "Ligevægtsbrøken:";
            // 
            // label10
            // 
            this.label10.Name = "label10";
            this.label10.Location = new System.Drawing.Point(368, 16);
            this.label10.Image = null;
            this.label10.TabIndex = 4;
            this.label10.Size = new System.Drawing.Size(128, 16);
            this.label10.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, (System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline), System.Drawing.GraphicsUnit.Point);
            this.label10.Text = "Idealgasligningen:";
            // 
            // label11
            // 
            this.label11.Name = "label11";
            this.label11.Location = new System.Drawing.Point(16, 224);
            this.label11.Image = null;
            this.label11.TabIndex = 5;
            this.label11.Size = new System.Drawing.Size(148, 16);
            this.label11.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, (System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline), System.Drawing.GraphicsUnit.Point);
            this.label11.Text = "Hastighedskonstanten:";
   //         this.label11.Click += new System.EventHandler(this.label11_Click);
            // 
            // label12
            // 
            this.label12.Name = "label12";
            this.label12.Location = new System.Drawing.Point(16, 264);
            this.label12.Image = null;
            this.label12.TabIndex = 6;
            this.label12.Size = new System.Drawing.Size(8, 16);
            this.label12.Text = "K";
            // 
            // label13
            // 
            this.label13.Name = "label13";
            this.label13.Location = new System.Drawing.Point(24, 272);
            this.label13.Image = null;
            this.label13.TabIndex = 7;
            this.label13.Size = new System.Drawing.Size(8, 8);
            this.label13.Font = new System.Drawing.Font("DejaVu Sans", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.label13.Text = "h";
            // 
            // label14
            // 
            this.label14.Name = "label14";
            this.label14.Location = new System.Drawing.Point(32, 264);
            this.label14.Image = null;
            this.label14.TabIndex = 8;
            this.label14.Size = new System.Drawing.Size(16, 16);
            this.label14.Text = "=";
            // 
            // label15
            // 
            this.label15.Name = "label15";
            this.label15.Location = new System.Drawing.Point(48, 264);
            this.label15.Image = null;
            this.label15.TabIndex = 9;
            this.label15.Size = new System.Drawing.Size(24, 16);
            this.label15.Text = "e ⁻";
            // 
            // label17
            // 
            this.label17.Name = "label17";
            this.label17.Location = new System.Drawing.Point(80, 248);
            this.label17.Image = null;
            this.label17.TabIndex = 11;
            this.label17.Size = new System.Drawing.Size(16, 16);
            this.label17.Text = "Eₐ";
            // 
            // label16
            // 
            this.label16.Name = "label16";
            this.label16.Location = new System.Drawing.Point(72, 256);
            this.label16.Image = null;
            this.label16.TabIndex = 12;
            this.label16.Size = new System.Drawing.Size(40, 16);
            this.label16.Text = "______";
         //   this.label16.Click += new System.EventHandler(this.label16_Click);
            // 
            // label18
            // 
            this.label18.Name = "label18";
            this.label18.Location = new System.Drawing.Point(72, 272);
            this.label18.Image = null;
            this.label18.TabIndex = 13;
            this.label18.Size = new System.Drawing.Size(32, 16);
            this.label18.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            this.label18.Text = "R • T";
            // 
            // label19
            // 
            this.label19.Name = "label19";
            this.label19.Location = new System.Drawing.Point(336, -8);
            this.label19.Image = null;
            this.label19.TabIndex = 14;
            this.label19.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.label19.Size = new System.Drawing.Size(15, 304);
            this.label19.Text = "";
   //        this.label19.Click += new System.EventHandler(this.label19_Click);
            // 
            // label20
            // 
            this.label20.Name = "label20";
            this.label20.Location = new System.Drawing.Point(16, 16);
            this.label20.Image = null;
            this.label20.TabIndex = 4;
            this.label20.Size = new System.Drawing.Size(128, 16);
            this.label20.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, (System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline), System.Drawing.GraphicsUnit.Point);
            this.label20.Text = "Idealgasligningen:";
            // 
            // label21
            // 
            this.partialpressure.Name = "label21";
            this.partialpressure.Location = new System.Drawing.Point(368, 56);
            this.partialpressure.Image = null;
            this.partialpressure.TabIndex = 15;
            this.partialpressure.Size = new System.Drawing.Size(48, 16);
            this.partialpressure.Text = "Partial";
			this.partialpressure.ContextMenu = cm;
			//this.partialpressureNitrogen.ContextMenu.MenuItems[1]. += new System.EventHandler (this.menuItem1_ItemClick);

			cm.MenuItems.Add ("Nitrogen");
			cm.MenuItems.Add ("Hydrogen");
			cm.MenuItems.Add ("Ammoniak");
		
			// 
            // label22
            // 
            this.label22.Name = "label22";
            this.label22.Location = new System.Drawing.Point(416, 56);
            this.label22.Image = null;
            this.label22.TabIndex = 16;
            this.label22.Size = new System.Drawing.Size(16, 16);
            this.label22.Text = "=";
            // 
            // label24
            // 
            this.molarmassNitrogen.Name = "label24";
            this.molarmassNitrogen.Location = new System.Drawing.Point(432, 40);
            this.molarmassNitrogen.Image = null;
            this.molarmassNitrogen.TabIndex = 18;
            this.molarmassNitrogen.Size = new System.Drawing.Size(64, 16);
            this.molarmassNitrogen.Text = "molar";
            // 
            // label23
            // 
            this.label23.Name = "label23";
            this.label23.Location = new System.Drawing.Point(72, 40);
            this.label23.Image = null;
            this.label23.TabIndex = 19;
            this.label23.Text = "label23";
            // 
            // label25
            // 
            this.label25.Name = "label25";
            this.label25.Location = new System.Drawing.Point(576, 40);
            this.label25.Image = null;
            this.label25.TabIndex = 20;
            this.label25.Size = new System.Drawing.Size(8, 16);
            this.label25.Text = "•";
            // 
            // label26
            // 
            this.gasConst.Name = "label26";
            this.gasConst.Location = new System.Drawing.Point(512, 40);
            this.gasConst.Image = null;
            this.gasConst.TabIndex = 21;
            this.gasConst.Size = new System.Drawing.Size(56, 16);
            this.gasConst.Text = gasConstant.ToString ();
            this.gasConst.Text = "gasConst";
            // 
            // label27
            // 
            this.label27.Name = "label27";
            this.label27.Location = new System.Drawing.Point(496, 40);
            this.label27.Image = null;
            this.label27.TabIndex = 20;
            this.label27.Size = new System.Drawing.Size(8, 16);
            this.label27.Text = "•";
            // 
            // label28
            // 
            this.temperature.Name = "label28";
            this.temperature.Location = new System.Drawing.Point(592, 40);
            this.temperature.Image = null;
            this.temperature.TabIndex = 22;
            this.temperature.Size = new System.Drawing.Size(40, 16);
            this.temperature.Text = "Temp";
            // 
            // label29
            // 
            this.label29.Name = "label29";
            this.label29.Location = new System.Drawing.Point(432, 48);
            this.label29.Image = null;
            this.label29.TabIndex = 23;
            this.label29.Size = new System.Drawing.Size(192, 15);
            this.label29.Text = "_________________________________";
            // 
            // label30
            // 
            this.Volume.Name = "label30";
            this.Volume.Location = new System.Drawing.Point(496, 64);
            this.Volume.Image = null;
            this.Volume.TabIndex = 24;
            this.Volume.Size = new System.Drawing.Size(56, 16);
            this.Volume.Text = volume.ToString ();
            this.Volume.Text = "Volumen";
            // 
            // label31
            // 
            this.label31.Name = "label31";
            this.label31.Location = new System.Drawing.Point(16, 120);
            this.label31.Image = null;
            this.label31.TabIndex = 4;
            this.label31.Size = new System.Drawing.Size(128, 16);
            this.label31.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, (System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline), System.Drawing.GraphicsUnit.Point);
            this.label31.Text = "Ligevægtsbrøken:";
            // 
            // CalcForm
            // 
            this.Name = "CalcForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.ClientSize = new System.Drawing.Size(681, 292);
            this.Location = new System.Drawing.Point(-104, 0);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label15);
            this.Controls.Add(this.label17);
            this.Controls.Add(this.label16);
            this.Controls.Add(this.label18);
            this.Controls.Add(this.label19);
            this.Controls.Add(this.label20);
            this.Controls.Add(this.partialpressure);
            this.Controls.Add(this.label22);
            this.Controls.Add(this.molarmassNitrogen);
            this.Controls.Add(this.label23);
            this.Controls.Add(this.label25);
            this.Controls.Add(this.gasConst);
            this.Controls.Add(this.label27);
            this.Controls.Add(this.temperature);
            this.Controls.Add(this.label29);
            this.Controls.Add(this.Volume);
            this.Controls.Add(this.label31);
            this.Text = "CalcForm";
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
        }
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.Label partialpressure;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.Label molarmassNitrogen;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.Label gasConst;
        private System.Windows.Forms.Label label27;
        private System.Windows.Forms.Label temperature;
        private System.Windows.Forms.Label label29;
        private System.Windows.Forms.Label Volume;
        private System.Windows.Forms.Label label31;
    }
    #endregion
}
